
import * as XLSX from 'xlsx';
import * as path from 'path';
import * as fs from 'fs';

// Helper to write file
function writeExcel(filename: string, data: any[][]) {
    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.aoa_to_sheet(data);
    XLSX.utils.book_append_sheet(wb, ws, "Sheet1");
    const filePath = path.join(process.cwd(), 'testdata', filename);
    XLSX.writeFile(wb, filePath);
    console.log(`✅ Generated: ${filename}`);
}

// 1. Standard Layout (Clean, similar to current training)
const standardData = [
    ["Business Unit", "Container Number", "Origin Port", "Destination Port", "ETA", "ETD", "Carrier", "Status"],
    ["Global Parts", "MSCU1234567", "CNNYC", "USLGB", "2023-10-15", "2023-09-01", "MSC", "In Transit"],
    ["Auto Corp", "MAEU9876543", "CNSHA", "USLAX", "2023-10-20", "2023-09-05", "Maersk", "Arrived"],
    ["Global Parts", "CMAU1122334", "CNNING", "USSAV", "2023-11-01", "2023-09-10", "CMA CGM", "Gate Out"],
    ["Tech Items", "COSU5566778", "CNYANT", "USNYC", "2023-10-30", "2023-09-15", "Cosco", "Vessel Departure"],
    ["Retail Co", "ONEU9988776", "JPTOK", "USSEA", "2023-10-12", "2023-09-02", "ONE", "Discharged"]
];

// 2. Messy Layout (Abbreviations, typos, missing rows at top)
const messyData = [
    ["Weekly Report generated by System X"], // Junk row 1
    ["CONFIDENTIAL DO NOT SHARE"],           // Junk row 2
    [],                                      // Empty row
    ["Cust Ref", "CNTR ID", "Pol", "Pod", "Est. Arr.", "Dep. Date", "Vessel", "Remaks"], // Typo in Remarks, abbr headers
    ["PO-1001", "MSCU-123456-7", "Shanghai", "Long Beach", "10/15/23", "09/01/23", "MSC GULSUN", "On time"],
    ["PO-1002", "MAEU-987654-3", "Ningbo", "Los Angeles", "10/20/23", "09/05/23", "MAERSK ALABAMA", "Delayed"],
    ["PO-1003", "CMAU-112233-4", "Yantian", "Savannah", "11/01/23", "09/10/23", "CMA CGM MARCO POLO", "Customs Hold"],
    ["PO-1004", "COSU-556677-8", "Qingdao", "New York", "10/30/23", "09/15/23", "COSCO SHIPPING", "Rolling"],
    ["PO-1005", "ONEU-998877-6", "Tokyo", "Seattle", "10/12/23", "09/02/23", "ONE APUS", "Storm damage"]
];

// 3. Verbose Layout (Long, descriptive headers)
const verboseData = [
    ["The Unique Identification Number of the Shipping Container", "The Port where the Cargo was Loaded", "The Final Port of Discharge", "Estimated Time of Arrival (ETA)", "Actual Time of Departure (ATD)", "Shipping Line Carrier Code", "Current Transport Stage"],
    ["MSCU1234567", "CNNYC", "USLGB", "2023-10-15", "2023-09-01", "MSCU", "Ocean Transit"],
    ["MAEU9876543", "CNSHA", "USLAX", "2023-10-20", "2023-09-05", "MAEU", "Port Arrival"],
    ["CMAU1122334", "CNNING", "USSAV", "2023-11-01", "2023-09-10", "CMDU", "Gate Out"],
    ["COSU5566778", "CNYANT", "USNYC", "2023-10-30", "2023-09-15", "COSU", "Deep Sea"],
    ["ONEU9988776", "JPTOK", "USSEA", "2023-10-12", "2023-09-02", "ONEY", "Terminal"]
];

// 4. Minimal Layout (Missing many optional fields, different order)
const minimalData = [
    ["Status", "Container#", "Typ", "Wgt"],
    ["FCL", "MSCU1234567", "40HC", "12000"],
    ["FCL", "MAEU9876543", "20GP", "8500"],
    ["LCL", "CMAU1122334", "40GP", "15000"],
    ["AIR", "COSU5566778", "45HC", "2200"],
    ["FCL", "ONEU9988776", "20ST", "9000"]
];

// 5. Nightmare Layout (Merged cells simulation - repeated blank cols, weird casing, random notes)
// Note: xlsx library handles CSV-like grid. Merged cells often appear as values in first cell, null in others.
const nightmareData = [
    ["SHIPPING REPORT", "", "", "", "", "", ""],
    ["Region: APAC", "", "Date: Q3", "", "", "", ""],
    ["ID", "LOCATIONS", "", "DATES", "", "DETAILS", ""], // Multi-header simulation?
    ["Container_No", "From (POL)", "To (POD)", "Est Arrival", "Act Depart", "Vsl Name", "Notes/Comments"],
    ["MSCU1234567", "CNNYC", "USLGB", "2023-10-15", "2023-09-01", "Gulsun", "Priority"],
    ["MAEU9876543", "CNSHA", "USLAX", "2023-10-20", "2023-09-05", "Alabama", ""],
    ["CMAU1122334", "CNNING", "USSAV", "2023-11-01", "2023-09-10", "Marco Polo", "Do not stack"],
    ["COSU5566778", "CNYANT", "USNYC", "2023-10-30", "2023-09-15", "Shipping", "Fragile"],
    ["ONEU9988776", "JPTOK", "USSEA", "10/12/2023", "09/02/2023", "Apus", "Check seal"]
];

function main() {
    console.log("🏭 Generating Test Data Files...");
    if (!fs.existsSync(path.join(process.cwd(), 'testdata'))) {
        fs.mkdirSync(path.join(process.cwd(), 'testdata'));
    }

    writeExcel('test_vendor_standard.xlsx', standardData);
    writeExcel('test_vendor_messy.xlsx', messyData);
    writeExcel('test_vendor_verbose.xlsx', verboseData);
    writeExcel('test_vendor_minimal.xlsx', minimalData);
    writeExcel('test_vendor_nightmare.xlsx', nightmareData);

    console.log("\n🎉 All 5 test files generated in /testdata folder!");
}

main();
